### ISSUE TITLE
Current state of configuration

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-bigquery-writer#1]
Accessible via `https://connection.keboola.com/admin/projects/{PROJECT_ID}/writers/keboola.wr-google-bigquery`.

A new empty configuration looks like this:

![image](https://cloud.githubusercontent.com/assets/497675/23261704/df013512-f9d7-11e6-8583-288a7fb0c6a9.png)

There are 3 sections:

 - **Authorization** - authorizes us to access your Google BigQuery
 - **Table Input Mapping** - specifies tables to write to BigQuery
 - **Configuration** - specifies how the tables will be written to BigQuerey (datatypes, etc)

# Authorization

Just click the **Authorize Account** button and follow the instructions. You will be redirected to Google to confirm the authorization. This is the only part that will be kept into the final version of the writer and it's UI.

# Table Input Mapping

You have to add manually all tables that you want to use in the Writer. Clicking on the **Add Table Input** button will open this window

![image](https://cloud.githubusercontent.com/assets/497675/23261857/9f0fe57e-f9d8-11e6-955a-4bb17b87fc06.png)

 - **Source** - select the table from Storage
 - **File name** - does not matter, but any two tables cannot share the same file name
 - **Columns** - specify all columns you want to use in the Writer. Column list here must match the column list specified later in the **Configuration** section.
 - **Days/Data filter** - can be set to any values, the exported CSV will be affected by these settings

You can add as many tables as you want, but you have to match all of them in the **Configuration** section.

# Configuration

Configuration is set manually in JSON format (for now). The top level structure is following

```json
{
  "project": "",
  "dataset": "",
  "tables": []
}
```

 - `project` - Google project ID
 - `dataset` - BigQuery dataset, will be created if the given dataset does not exists
 - `tables` - Array of `table` objects, explained further

## Table object
```json
{
  "tableId": "",
  "dbName": "",
  "export": true,
  "incremental": true,
  "items": []
}
```
 - `tableId` - matches table id from the **Table Input Mapping** section
 - `dbName` - name of the table created in BigQuery
 - `export` - `true` or `false`, turns off processing of the current table
 - `incremental` - `true` or `false`, will overwrite or append to the table in BigQuery
 - `items` - Array of `datatype` objects, explained further

## Datatype
```json
{
  "name": "",
  "dbName": "",
  "type": ""
}
```
 - `name` - column name in Storage
 - `dbName` - column name in BigQuery
 - `type` - BigQuery column datatype, one of `STRING`, `INTEGER`, `FLOAT`, `BOOLEAN`, `TIMESTAMP`

## Example

```json
{
    "project": "syrup-components",
    "dataset": "najlos_dev",
    "tables": [
        {
            "dbName": "table1",
            "export": true,
            "tableId": "in.c-bucket.table1",
            "items": [
                {
                    "name": "string",
                    "dbName": "string",
                    "type": "STRING"
                },
                {
                    "name": "integer",
                    "dbName": "integer",
                    "type": "INTEGER"
                },
                {
                    "name": "float",
                    "dbName": "float",
                    "type": "FLOAT"
                },
                {
                    "name": "boolean",
                    "dbName": "boolean",
                    "type": "BOOLEAN"
                },
                {
                    "name": "timestamp",
                    "dbName": "timestamp",
                    "type": "TIMESTAMP"
                }
            ]
        }
    ]
}
```

![94087266-f9df-11e6-8574-0a1503120dbe](https://cloud.githubusercontent.com/assets/497675/23394981/5e57460a-fd8c-11e6-9640-d8e7110153e7.png)

# Misc & Rules

 - All columns of the table specified in the **Table Input Mapping** must be defined in the respective `table`.`datatype` in **Parameters**
 - All tables specified in the **Table Input Mapping** must be defined in the **Parameters**
 - All column/table/dataset names must follow BigQuery rules
 - Multiple configurations can share the same project/dataset, so you can use multiple writers to write into a single dataset
 - Incremental write to BigQuery will append all rows in the CSV file to the table in BigQuery. No deduplication. If the table is not incremental, writer will delete and recreate the table every time
 - Writer does not delete or affect in any way tables not specified in its configuration. 
 - Writer does not execute any SQL.
 - Tables are uploaded directly to BigQuery
 - There is a 3600s limit for processing any uploaded table in BigQuery. This limit does not include the time to upload the table.
 - All columns are set as `NULLABLE`.

**Comment by odinuv** [comment]
The configuration should not be nested in `parameters` field.

**Comment by ondrejhlavacek** [comment]
Thanks for noticing, will fix the screenshot!

**Comment by ondrejhlavacek** [comment]
Moved to Wiki: https://github.com/keboola/google-bigquery-writer/wiki/Configuration
