### ISSUE TITLE
add IGNORE type 

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-bigquery-writer#10]
nový datový typ IGNORE, kterej udělá totéž, jako když sloupec není definovanej

**Comment by ondrejhlavacek** [comment]
1) test, který ověří nezávislost pořadí sloupců
2) test, který ověří, že sloupec, který nemá schéma, ale je v CSV, nevyhodí chybu a nenahraje tam nedefinovaný sloupec

**Comment by Actimel** [comment]
ad 1/ Zamenit poradi sloupcu nejde, importuje se to tam v poradi, jeke je v csv.
ad 2/ Kdyz je v csv vice sloupcu nez v definici, data to nenahraje.

Takze se vracime k puvodnimu issue, kde se musi sloupce, ktere do Bigquery nechceme vydefinovat priznakem `IGNORE` a nasledne tam ty data osekat a nastreamovat.

Nicmene se muzeme bezpecne odpichnout od toho, ze poradi je striktni.

**Comment by ondrejhlavacek** [comment]
Díky za průzkum! Hnedka máme na stole několik dalších problému.

- Pořadí sloupců v konfiguraci se může lišit od sloupců v CSV, a to se všechno ještě může lišit od sloupců v BigQuery. Všechno je potřeba zkontrolovat a seřadit. 
- Počet sloupců se může lišit také ve všech případech. V téhle situaci je potřeba vyhodit chybu a říct něco srozumitelného uživateli, kromě případu, kdy je CSV víc sloupců než v konfiguraci, potom bych sloupce navíc bral jako IGNORE

Pokud by to bylo pro tebe jednodušší, můžeme to celý zrefaktorovat do PHP, není žádnej důvod, proč by to mělo být v Pythonu.

**Comment by ondrejhlavacek** [comment]
Sestavuju UI a koukám, že sloupce, které jsou IGNORE, tak se do konfigurace vůbec nezapíšou. Navíc se UI postará o to, aby sloupce v CSV vůbec nebyly (v input mappingu je vyfiltruje). Tím se to dost zjednodušuje. Můžeme teda říct, že

a) CSV obsahuje jen ty sloupce, který jsou zkonfigurovaný, a každej sloupec v CSV má datový typ (není IGNORE). 
b) Pořadí sloupců v CSV a v konfiguraci nemusí mít stejné pořadí.

Stačí teda vyřešit, aby sloupce byly zapisovány do BigQuery ve správném pořadí (je jedno, jestli má prioritu CSV nebo konfigurace). 

U inkrementálního zápisu (přidání záznamů do existující tabulky) je potřeba navíc zkontrolovat že schéma v BigQuery odpovídá sloupců v CSV/konfiguraci. Pokud nesedí, vyhodit `UserException`. 
U neinkrementálního zápisu tabulku pokaždé dropujeme a vytváříme novou.

**Comment by Actimel** [comment]
ad a/
Tim padem je to vyresene, ale jeste to overim

ad b/
Upravil jsem generovani schematu pro BigQuery, ktere se bude zavisle na poradi sloupcu v .csv. Takze i kdyz konfigurece cloupcu bude klidne v nahodnem poradi, tak podle hlavicky .csv si to seradim jak se slusi a patri.

U novyh tabulek to cele uz je bez problemu, ale zbyva mi udelat porovnani poradi sloupcu .csv a BigQuery v pripade, ze jiz tabulka existuje a nevytvarime nove schema.
