### ISSUE TITLE
Empty project or dataset should be user err

### ISSUE THREAD

**Issue by ujovlado** [keboola/google-bigquery-writer#17]
`docker-133625e521f9e4082bbc78c64ecda8b0`

**Comment by ujovlado** [comment]
hm, but it looks like it failed sooner? 

```
(2) Unhandled exception: 'destination'
Traceback (most recent call last):
File "./main.py", line 11, in main
application.ru ... ib/python3.6/site-packages/keboola/docker.py", line 198, in get_input_tables
table['destination']
KeyError: 'destination'
```

**Comment by ujovlado** [comment]
I filled both project and dataset (with random values) and it fails with same err. So maybe it is not related to these, but to keboola package itself.

I don't want to point to wrong direction, so checking exception itself for further debugging will be the better choice.

**Comment by ondrejhlavacek** [comment]
Zajímavý, že test na to je - https://github.com/keboola/google-bigquery-writer/blob/64360c32ecf50a01bb84c1ec07662fc5e9869597/test/test_writer_errors.py#L154

**Comment by ondrejhlavacek** [comment]
Tak je to něčím jiným, v konfiguraci chybí `destination`

```
{
          "source": "in.c-htns-ex-salesforce-213363142.User",
          "changed_since": "",
          "columns": [
            "Id",
            "Name"
          ]
        }
```
=>
```
{
          "source": "in.c-htns-ex-salesforce-213363142.User",
          "destination": "User.csv",
          "changed_since": "",
          "columns": [
            "Id",
            "Name"
          ]
        }
```
